### ISSUE TITLE
divide DwC properties into object properties and data properties

### ISSUE THREAD

**Issue by ramonawalls** [BiodiversityOntologies/bco#10]
Those that have a class in the range should be object properties. Those that have a literal should be data properties.

**Comment by rlwalls2008** [comment]
We also need to deal with the fact that there are two copies of all DwC properties - one in the dwc namespace and one in the dwciri namespace.

**Comment by rlwalls2008** [comment]
Note that for some of the DwC properties, we probably want to create corresponding classes.

**Comment by cmungall** [comment]
I feel there must be a community standard already for all this?

I generally play fast and loose with the dcs, use them for lightweight ontology annotations, by default they get crammed into APs. But this has the potential to conflict with other interpretations that make them DPs, OPs?

I feel there should be a pan-semweb standard that shadows commonly used rdf vocabularies into their owl counterparts. The shadow-owl world if you will.

**Comment by dr-shorthair** [comment]
> Those that have a class in the range should be object properties. Those that have a literal should be data properties.

And some _but not all_ should also be annotation-properties (APs), as @cmungall has pointed out.

**Comment by ramonawalls** [comment]
There is no need to do the division. As described in https://dwc.tdwg.org/rdf, DwC uses two different name spaces. Anything in the `dwc:` namespace should be a data property (with a literal value). Anything in the `dwciri:` namespace should be an object property (with an instance IRI as the value). I will create OWL files for both of these namespaces, from which we can import either object or data properties as needed.  This will be handled in issue #107 .

Note that DwC *does not* specify domains or ranges for any of the properties. We may choose to do so within the specific context of BCO.
