### ISSUE TITLE
FAIRsharing query - BCO

### ISSUE THREAD

**Issue by allysonlister** [BiodiversityOntologies/bco#106]
Dear Ramona, BCO Developers,

I’m contacting you on behalf of FAIRsharing[1], the online registry of scientific data standards, databases and policies. Our aim is to make your resource as visible as possible to as large an audience as possible.

We have a FAIRsharing record for your resource[2]. To ensure our information is as correct and up to date as possible, would you or someone from your team quickly scan the record[2] and ‘claim’ it? (To claim, see link [3] below.)

Claiming a record as either a group or an individual also gives you the opportunity to make changes to the record yourself, allowing you complete control over how your resource is displayed in FAIRsharing. In addition, if you claim a record(s) as an individual, you can link the record to your ORCID.

FAIRsharing is about making your resource discoverable to a variety of users, such as journals and publishers, researchers and service providers, research and infrastructure projects and programmes, as well as curators, librarians, funders and other policy makers and data scientists[4]. A contact is essential should they have any questions about your resource.

Thank you and best wishes,
Allyson

[1] https://fairsharing.org, https://doi.org/10.1038/s41587-019-0080-8
[2] https://doi.org/10.25504/FAIRsharing.8ktkqy
[3] https://fairsharing.org/own/standard/claim/bsg-s000827
[4] https://fairsharing.org/communities

**Comment by ramonawalls** [comment]
Done! I have claimed it.

**Comment by allysonlister** [comment]
Thanks so much! Feel free to contact us at contact@fairsharing.org if you have any questions.

Best wishes,
Allyson
