### ISSUE TITLE
New Basis of Record term "zooarchaeological specimen"

### ISSUE THREAD

**Issue by robgur** [BiodiversityOntologies/bco#28]
I am proposing a new Basis of Record term for BCO.  

BCO preferred term: ZooarchaeologicalSpecimen

alternative terms: none.  Although "Zoo" is specific to animals and "Archaeobotanical" is used for  plants.  Bioarchaeological is not a good catch-all phrase because it is used in the community of practice to refer to only human remains. 

textual definition:  A preserved specimen that is the output of an archaeological sampling process.  

definition source for the textual definition (preferably a DOI, URI, or ISBN #):  Rob Guralnick

logical definition (or parent term):  PreservedSpecimen

example(S) of usage:   ZooarchaeologicalSpecimens are typically collections of biological material generated as part of an archaeological collecting process that is separate from the type of processes that would yield other kinds of samples or collections of samples.  This process almost always entails collecting in-situ from archaeological sites where there is evidence of past human material culture.  Example:  A set of gastropod and bivalve shells found in shell midden from an archaeological site in Alaska would each have as a basis of record "ZooarchaeologicalSpecimen".  

term editor: Robert Guralnick

**Comment by ramonawalls** [comment]
We will define zooarcheological specimen to be specific to animal remains and also add a term for archeobotanical specimen that is for plant remains.

At some point, it would be good to import a process for archeological specimen collection from an authoritative source and make these specimens an output of it.

**Comment by ramonawalls** [comment]
New terms added with commit 5792528.
