### ISSUE TITLE
New term request: origin and establishment status

### ISSUE THREAD

**Issue by qgroom** [BiodiversityOntologies/bco#30]
On specimens and in Floras one often comes across comments such as 'introduced', 'casual', 'native', 'planted', 'escaped', which give information about the origin of the organism at the site. These terms are also related to how well established the organism is at the site, but there are additional terms such as 'persisting', 'spreading', 'invasive', 'relic', which relate only to how well established the organism is at the site and if it is reproducing.

Requires some investigation to find out where terms such as neophyte and archaeophyte come from and whether there are preexisting vocabularies.

**Comment by qgroom** [comment]
A similar terminology also exists for birds.

Permanent Resident
Winter Resident
Summer Resident
Transient
Migrant
Irregular Visitor
Vagrant

**Comment by tucotuco** [comment]
Can we relate this to Darwin Core's establishmentMeans and work out how the semantics would change?

http://rs.tdwg.org/dwc/terms/index.htm#establishmentMeans

**Comment by qgroom** [comment]
establishmentMean is certainly part of it, although DwC establishmentMean needs some work. The suggested vocabulary includes words like "naturalized", "invasive" and "managed, which are not means of establishment, but expressions of how well established the organism is at the site. I feel we need to separate the mechanism by which an organism got to the site from how well established it is.

**Comment by tucotuco** [comment]
Can we make a couple of term names to begin to work with to make the distinction? I propose keeping establishmentMeans and propose a more specific definition, with examples of what it is and what it isn't.

**Comment by rlwalls2008** [comment]
This will stay here for now, but these terms will eventually end up in PCO and maybe some in ENVO.

**Comment by ramonawalls** [comment]
Closing this issue, and moving to PopulationAndCommunityOntology/pco#49
