### ISSUE TITLE
Find existing term for 'printed report'

### ISSUE THREAD

**Issue by tucotuco** [BiodiversityOntologies/bco#34]
Replace term 'printed report' with a term from IAO (document?).

**Comment by tucotuco** [comment]
IAO has apparently is a bit confusing, or has changed somewhat from what we have written in the bco:printed report comment:

"IAO has the term document, which is defined as "A collection of information content entities intended to be understood together as a whole" and has as examples journal article, patent application, laboratory notebook, and book.  IAO also has a term for report, but it is not defined. With this term, we want to describe the physical object that corresponds to some information content entity, together with the information content contained in the document or report. This class may be less important for modeling collection data, but could be important for efforts to get hand written (specifically dependent) reports into an electronic (generically dependent) report, and monitoring that process."

In IAO, we have 'document'

http://www.ontobee.org/browser/rdf.php?o=IAO&iri=http://purl.obolibrary.org/obo/IAO_0000310

with subclass 'report'

http://www.ontobee.org/browser/rdf.php?o=IAO&iri=http://purl.obolibrary.org/obo/IAO_0000088

which has 'journal article' as a subclass. Looks like we do not have exactly what we are looking for in IAO.

**Comment by ramonawalls** [comment]
OBI now has Term IRI: http://purl.obolibrary.org/obo/OBI_0000044 (physical document), which would make a good parent for this.

**Comment by ramonawalls** [comment]
We have yet to have a need for this term, so I am inclined to close this issue. What do you think, @tucotuco?

**Comment by ramonawalls** [comment]
I am going to import OBI:physical document .
