### ISSUE TITLE
OBI imports file is out of date, inconsistent with RO

### ISSUE THREAD

**Issue by robgur** [BiodiversityOntologies/bco#38]
Need to update OBI_imports file from the latest version of OBI which should be consistent with RO,  but the current version of OntoFox has the old version.   If this takes too long, we will use another tool to crack this particular nut with OBI imports.

**Comment by rlwalls2008** [comment]
OBI is not yet using RO relations, and still uses old BFO relations. For now, we will have to stick with manual corrections of the OBI imports.

**Comment by ramonawalls** [comment]
Fixed with new OBI import file
