### ISSUE TITLE
Update taxonomic inventory sources

### ISSUE THREAD

**Issue by tucotuco** [BiodiversityOntologies/bco#58]
When the paper comes out. Right now they point to the outdated Google spreadsheet.

**Comment by ramonawalls** [comment]
Also need to make sure that definitions in BCO match what is in paper.

1)    Restricted Search: A taxonomic inventory process that is restricted to plots, transects, or points, in which a person or group of people is comprehensively covering the entire area, usually with a well-described survey time or pace. The search is restricted to a defined and human-scale geospatial area (usually traversable within a time course of less than a day) within which there is an expectation of a comprehensive accounting of the taxonomic items of interest.

2)    Open Search: A taxonomic inventory process in which the search is restricted within a larger defined geographic area, but where effort isn't even or complete across the region, and thus not a comprehensive accounting of taxa of interest. Temporal duration is typically longer than restricted searches, lasting hours to several days.

3)    Opportunistic Search: A taxonomic inventory process that is a more casual reporting of occurrences of taxa of interest, still intended to be a comprehensive accounting of the taxa of interest, but with no pre-specified investment of effort nor planned trajectory for discovery, thus of often idiosyncratic length or spatial scope.

4)    Trap or sample inventory: A taxonomic inventory process that is typically restricted in geospatial extent that involves either the physical extraction of some evidence of the presence of the taxa of interest, such as a whole organisms, scat, fur, other material samples or information artifacts such as photographs or sound recordings

5)    Incidental/adventitious: A taxonomic inventory process in which taxon occurrences are recorded as co-variates of another study, or by happenstance, and later compiled as a taxonomic inventory.

**Comment by ramonawalls** [comment]
http://onlinelibrary.wiley.com/doi/10.1111/ecog.02942/full
