### ISSUE TITLE
Move this repo to a new organization

### ISSUE THREAD

**Issue by rlwalls2008** [BiodiversityOntologies/bco#69]
The plan is to create an organization for BCO and move the repo under there. This is a heads up. Github should redirect from this location: https://github.com/blog/1508-repository-redirects-are-here.

I will send an announcement to bco-discuss when it is imminent.

**Comment by rlwalls2008** [comment]
@tucotuco - I cannot move this repo, because I am not the owner. Will you please move it to the new organization BiodiversityOntologies? I just sent you an invite to join that organization. It is ready to move whenever you get a chance.

**Comment by tucotuco** [comment]
Done
