### ISSUE TITLE
NTRs: overcrowded

### ISSUE THREAD

**Issue by cmungall** [BiodiversityOntologies/bco#71]
Should `overcrowded` go in PATO?

We need a generic `density` in PATO (`mass density` is not appropriate here)

If OK, I can easily add

 * pop of population of organisms
    * density of pop
       * increased density of pop (aka overcrowded)
       * -

to PATO

unless you think it belongs here

**Comment by rlwalls2008** [comment]
Looks like this issue was intended for PCO, not BCO. I will copy it there.
