### ISSUE TITLE
Incorrect BFO URI

### ISSUE THREAD

**Issue by cmungall** [BiodiversityOntologies/bco#72]
how was http://purl.obolibrary.org/obo/bco/obi_bco_imports.owl created?

it has some non-existent URIs,  e.g

```
obo:BFO_0000053 rdf:type owl:ObjectProperty ;                
                rdfs:label "is bearer of"@en ;
```

I recommend RO_0000053 "bearer of"

BFO_0000053 I believe was originally 'bearer of at all times', but this is not in the current release of BFO

**Comment by ramonawalls** [comment]
This was fixed by updating the OBI import file.
