### ISSUE TITLE
inconsistent OBO ID space

### ISSUE THREAD

**Issue by stuckyb** [BiodiversityOntologies/bco#74]
Terms in BCO do not all have the same OBO ID space.  Some use "BCO" (e.g., "human observation process") and some use "bco" (e.g., "observing process").  The [OBO Foundry ID Policy](http://www.obofoundry.org/id-policy.html) suggests that these ID spaces are intended to be case sensitive, so BCO currently has terms in 2 ID spaces, which is bad for obvious reasons.

**Comment by cmungall** [comment]
I thought this was fixed here: #66

**Comment by stuckyb** [comment]
It looks like it was, but that fix has not propagated to an actual release.  The version at http://purl.obolibrary.org/obo/bco.owl does not have the fix.

**Comment by ramonawalls** [comment]
working on a new release that will fix this

**Comment by ramonawalls** [comment]
will be propagated with next release
