### ISSUE TITLE
'has role' redundancy

### ISSUE THREAD

**Issue by stuckyb** [BiodiversityOntologies/bco#76]
BCO includes three versions of 'has role': BCO:0000058, BFO:0000087, and RO:0000087.  As far as I can tell, 'has role' has been removed from BFO, so BFO:0000087 is no longer valid and should be deleted from BCO.  The BCO 'has role' appears to be very similar to, and possibly conceptually identical to, the RO version.  I suspect the BCO version should be deleted.

**Comment by ramonawalls** [comment]
Fixed by updating OBI import and removing redundant BCO relation.

**Comment by ramonawalls** [comment]
There is still a BCO term with the label has role. Need to deprecate it.
