### ISSUE TITLE
taxonomic identification process subclass of observing process

### ISSUE THREAD

**Issue by ramonawalls** [BiodiversityOntologies/bco#80]
Observing process is defined as "A process in which a person or machine sees or detects a material entity and selects it as worthy of observation, and which has as output an information content entity about the selected material entity." which covers bco:taxonomic identification process and its equivalent class dwc:Identification.

**Comment by ramonawalls** [comment]
@robgur and @tucotuco please advise if you agree or disagree.

**Comment by robgur** [comment]
I think I agree, as a broad definition of "observing process".  I am not
sure if it has to be a material sample that is observed.

**Comment by ramonawalls** [comment]
@robgur  - It's not a material sample, just a material entity. Means that we can't observe processes directly, only the material entities that participate in those processes. A difference from OBOE. However, and observing process can still have output about a process.

**Comment by robgur** [comment]
Ah, of course!
