### ISSUE TITLE
Project to add sites and site-visits

### ISSUE THREAD

**Issue by dr-shorthair** [BiodiversityOntologies/bco#82]
We are looking at making some extensions to accommodate **ecological observations**. These tend to be organized around **sites**. Those sometimes host instruments `ERO_0000004` for continuous monitoring, but more often are associated with **site-visits** during which one or more observations are made `BCO_0000003` or specimens collected `OBI_0000659`. An ecological observations site (the place you drive or walk to) often has sub-sites, plots, quadrats, traps, transects (where the technical work is done). 

We expect that this will involve 
- a  small number of sub-classes of **site** `BFO_0000029`
- a sub-class of **planned process** `OBI_0000011` and **environmental monitoring** `ENVO_01001170`
- use of, or specialization of relationships from RO (**causal** `RO_0002410`, **mereotopological** `RO_0002323` and **temporal** `RO_0002222` ) to link sites, sub-sites, visits, instruments, and the processes carried out during a visit

My hunch is that this all fits nicely in the scope of BCO, but will work in a new namespace if that is preferred. 

Meanwhile, I'll have to brush up on my Protege skills as I'm normally a TopBraid user ;-)

**Comment by pbuttigieg** [comment]
Linking to revisions in ENVO to support `environmental monitoring` and related processes.

> a small number of sub-classes of site BFO_0000029

ENVO has the `environmental zone` branch which may be useful for these. It specifies the BFO:site and uses subclass axioms to express what physical entities it overlaps. We'd be happy to host any classes you need, linking back to your ORCID and project identifiers.

**Comment by pbuttigieg** [comment]
@dr-shorthair  @ramonawalls 

I think BCO should have classes under an `ecosystem observation` axiomatised with ENVO's `ecosystem`. This can be specified quite systematically using other environments or environmental zones. 

I was thinking of adding this to ENVO, but BCO is the better home for this. I also have no objection to moving `environmental monitoring` et al. to BCO

**Comment by ramonawalls** [comment]
Well, @dr-shorthair, we can't all afford such fancy software! Actually, I hope to move to a more automated build process at some point soon, which should allow new terms to be created outside Protege.

I agree that BCO is a good place to host classes for `ecological observations`. My concern is that the phrase is extremely broad, and could encompass all kinds of observations for many different purposes. @pbuttigieg 's suggestion for `ecosystem observations` is a good start at being more specific, but it may not encompass everything that you have in mind.

Note that bco `observing process` is not restricted to human observations, and can include observations by machine sensors.

Regarding things like site visits, I would love to expand on those further. We have some really simple (i.e. not logically defined) classes for `taxonomic observing process` that include the idea of site visits, so we could use the logic there as well. People are getting more interested in using Darwin core to describe various sampling and observing protocols, so the time is right to get these semantics worked out.

@dr-shorthair, when you are ready to dive into this, let me know if you want to set up a call.

**Comment by dr-shorthair** [comment]
> may not encompass everything that you have in mind

I will be guided by actual practice here. We are primarily wanting to capture the processes used in (often state agency based) surveys, monitoring and campaigns. We have a lot of data to test it against. 

Some of these practices feature dependencies between site-visits and observations that are not necessarily interesting scientifically, but are useful for management and discovery. `RO_0002427` **causally downstream of or within** might be used to link observation and specimen collection processes to a site-visit. Not sure that scenario was envisaged by @cmungall though ...

**Comment by dr-shorthair** [comment]
OK @ramonawalls @pbuttigieg @robgur - I'm ready to dive in. With our geographic distribution, I suspect 20:00 UTC is the only practical time for a call.

**Comment by ramonawalls** [comment]
Thanks, @dr-shorthair. Back from vacation and recovering from my cold, so I'm also ready to dive it. 

@pbuttigieg Can you do 20:00 UTC (21:00 CET, I guess) any day in the coming week? @robgur That is 4PM for you. Which days are you available (or not). 

I can do any day between now and 9/21 at that time except Monday 9/17 and Thursday 9/20 (presumably 1 day later for Simon). If we can't all make it, we'll start with just Simon and I.

**Comment by robgur** [comment]
I will try to make it.
-r

**Comment by dr-shorthair** [comment]
Wednesday, Thursday and Friday (actually Thursday, Friday and Saturday ;-) ) no good for me. , so it'd best be Tuesday (Wednesday) at 20:00 UTC. I'll send an invitation.

**Comment by tucotuco** [comment]
I'm still lost in NZ but should be unlost by the 18th, Argentina time. May
I please be included in the invitation as well?

**Comment by ramonawalls** [comment]
Happy to have you on the call, John! I'll forward the invite to you.

Ramona
------------------------------------------------------
Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by dr-shorthair** [comment]
Renamed this issue to reflect the fact that most of the chat is about project initiation and organizing a meeting. Assume we will create more detailed issues for substantive work.

**Comment by pbuttigieg** [comment]
Teleconference concluded with @ramonawalls @tucotuco @dr-shorthair and Guru in attendance. 
Further issues to address this use case will be posted on the BCO tracker and cross-linked with ENVO as needed. BCO will handle the semantics of the "visits" and ENVO of the "sites" (save for sites with fiat boundaries defined by acts of observation such as transects, which will reside in BCO).

**Comment by robgur** [comment]
Excellent outcome!  Sorry to miss this...

**Comment by dr-shorthair** [comment]
I'll close this issue, and get going with more atomic requests.
