### ISSUE TITLE
removed  un-needed OBI and BFO classes

### ISSUE THREAD

**Issue by ramonawalls** [BiodiversityOntologies/bco#9]
This was suggested by Melissa at our last hackathon. It will make the ontology easier to navigate, but there is no real harm in having them there (except maybe scaring off users).

**Comment by rlwalls2008** [comment]
I think we need to keep the BFO and OBI classes in the editor's version, but we can make a pared down release.

**Comment by ramonawalls** [comment]
Given the current uses and users of BCO, and its intended audience (i.e. ontology developers), I don't see an strong reason to remove the upper level classes. If a use case comes up for this it can be revisited.
