### ISSUE TITLE
Check and fix BCO use of obo:bfo_site

### ISSUE THREAD

**Issue by ramonawalls** [BiodiversityOntologies/bco#91]
Today I heard the BFO developers explained the difference between site and spatial region (which are sibling classes of parent immaterial entity). Site is intended for use when referring to a non-material entity whose location is defined by a material entity or entities that bound it (e.g., a cavity). Spatial region is intended for an immaterial entities whose locations are defined by a coordinate system (e.g., geographic coordinates or the surface of the body, as two example). Therefore, I think we have often been using bfo:site in BCO where we should be using spatial region.

We need to check how this impacts the mapping to dwc:location, and other terms.

**Comment by dr-shorthair** [comment]
In both cases there is a spatial-reference-system. In the first case this is tied to other entities. In the second it is tied to a spatial frame.

**Comment by robgur** [comment]
+1 to Ramona's assessment that we mean spatial region not site based on the
bfo defintions.

**Comment by ramonawalls** [comment]
True, @dr-shorthair. I was being lazy in my choice of wording. Frame is exactly the word used with spatial region. Here are the actual elucidations:

b is a site means: b is a three-dimensional immaterial entity that is (partially or wholly) bounded by a material entity or it is a three-dimensional immaterial part thereof. (axiom label in BFO2 Reference: [034-002])

A spatial region is a continuant entity that is a continuant_part_of spaceR as defined relative to some frame R. (axiom label in BFO2 Reference: [035-001])

One might argue that there are non-material entities that are both sites and spatial regions based on those elucidations, but the classes are disjoint in BFO, so that is clearly not the intention.

**Comment by tucotuco** [comment]
Is a country a site or a spatial region?  The answer matters with respect
to Darwin Core, because both dwc:country and dwc:footprintWKT (as a
representative spatial region) are "organized in" the dcterms:Location
class. Is dcterms:Location a site or a spatial region?

**Comment by ramonawalls** [comment]
@tucotuco Currently, we specify that bfo:site is equivalent to dcterms:location, and I now think that is wrong. I'm not yet ready to commit to a new mapping, but maybe union of bfo:site and bfo:spatial region. I bet the bulk of dwc properties describe spatial regions, not sites, but there may be a few sites in there as well, so we need to look into it carefully.

In answer to your question, I don't think a country is a site or a spatial region, although it certainly occupied a spacial region. However, I think what you were referring to is whether dwcterms:country is a property of a spatial region or site. I'm pretty sure it is a spatial region nearly all the time.

**Comment by tucotuco** [comment]
I am good with "dwc:country is a property of a spatial region".  Though we
may not always have enough information in the properties of a
dcterms:Location to delineate its spatial region, I think we do intend for
it to be one in Darwin Core.

**Comment by pbuttigieg** [comment]
Slippery classes here. The common term term "country" can refer to bothering a site and a spatial region (which can overlap) , but I think the geopolitical usage meant in DwC is indeed more about later/lon rather than "mountains to the east, sea to the west ". Thus spatial region sounds better.

**Comment by dr-shorthair** [comment]
I suspect that country-name is often used as a proxy for its geospatial footprint. I.e. it is the spatial thing that we want to denote, but it is convenient to use the country name to do that (because strings of coordinates are difficult). 

https://youtu.be/gtLxZiiuaXs

**Comment by dr-shorthair** [comment]
So the intention is 'the desired location is the same as the location of the entity known as Transylstan' where Transylstan is the label of an entity which also has a location/shape property.

**Comment by pbuttigieg** [comment]
@dr-shorthair yes, a gazetteer of some sort is the best bet here. GAZ is being activated again, but I'm not sure about the ETA.
